### ISSUE TITLE
Gravity Forms Column Classes

### ISSUE THREAD

**Issue by robertallenbaker** [abrudtkuhl/WordPress-Bootstrap-Gravity-Forms#7]
Hi there,

First off, thank you for making this.  This is extremely helpful!  I was wondering, though, what about forms with Gravity Forms Column classes in them?  Once the CSS inside Gravity Forms is turned off these no longer function.

For example:
gf_left_half
gf_right_half

gf_one_third
gf_one_third_last, etc...

How are these addressed in this CSS?

**Comment by abrudtkuhl** [comment]
hmmm they arent :)

**Comment by robertallenbaker** [comment]
Strange.  When I turn off the CSS for Gravity Forms to get this great experience the form fields are full width.  Do I not turn off CSS for GF then?

**Comment by abrudtkuhl** [comment]
hmm it's been awhile :) i'll test that and get back to you

**Comment by BrandiHernandez** [comment]
Leave the settings 'turned on' to allow CSS for Gravity Forms to apply the columns within the fields.
